language: node_js

sudo: false

cache:
  directories:
    - node_modules

jobs:
  include:
    - stage: install
      name: 'Installation Stage'
      script: npm install
    - stage: test
      name: 'Testing the test cases'
      script: npm run test
    - stage: build
      name: 'Build Stage'
      script: npm run build